# Generated by Django 5.1.7 on 2025-03-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcare',
            old_name='rate',
            new_name='price_rate',
        ),
    ]
